### ISSUE TITLE
CSS Color Hex code logic required.

### ISSUE THREAD

**Issue by manolingam** [manolingam/background_generator#1]
Add a logic to display the hex code of the background color generated in the website.

**Comment by jarcelao** [comment]
Would like to take this one! Where exactly in the website would you like the hex string to be placed?

**Comment by manolingam** [comment]
> 
> 
> Would like to take this one! Where exactly in the website would you like the hex string to be placed?

Sure, go ahead. I want it to be placed below the current background text. Also make sure that the current background displays the default background hex when the website loads for first time.

**Comment by manolingam** [comment]
Issue solved by @victorcerutti . Closing this issue.
