### ISSUE TITLE
Button styling required.

### ISSUE THREAD

**Issue by manolingam** [manolingam/background_generator#4]
I want someone to style the two buttons in the webpage. It's default by now.

**Comment by harryandriyan** [comment]
I'll do it

**Comment by manolingam** [comment]
Go ahead.

**Comment by Adityakanyal** [comment]
Can I take this?

**Comment by manolingam** [comment]
Anyone can take.

**Comment by harryandriyan** [comment]
I make PR, please check it @manolingam

**Comment by manolingam** [comment]
Well done! @harryandriyan

**Comment by manolingam** [comment]
Issue solved by @harryandriyan Closing this issue!
